org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.injected.signing.enableV1=true
android.injected.signing.enableV2=true
android.injected.signing.enableV3=true
org.gradle.java.home=/Users/shaikhasfak/Library/Java/JavaVirtualMachines/ms-17.0.15/Contents/Home

